// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcPY3p78SMlrqFNnD-ml7RNyp0Mf_UDAo',
    appId: '1:1084165256050:android:353cc7f27d2b56af1c63eb',
    messagingSenderId: '1084165256050',
    projectId: 'chatapp-aaf41',
    storageBucket: 'chatapp-aaf41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaAt8wAuWXbaPjimktQQ2L9Opco4Jh3ng',
    appId: '1:1084165256050:ios:053e8a5603b331491c63eb',
    messagingSenderId: '1084165256050',
    projectId: 'chatapp-aaf41',
    storageBucket: 'chatapp-aaf41.firebasestorage.app',
    androidClientId: '1084165256050-nvj2b3traakpgk699tlp1ap8p4to5vc7.apps.googleusercontent.com',
    iosClientId: '1084165256050-5ldnekut3dlt1a1736o6b0o55qb0288k.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitchat',
  );

}